[2025-04-04T11:41:04.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-04T11:41:04.191+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-04T11:40:19.330331+00:00 [queued]>
[2025-04-04T11:41:04.201+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-04T11:40:19.330331+00:00 [queued]>
[2025-04-04T11:41:04.202+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-04T11:41:04.214+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-04 11:40:19.330331+00:00
[2025-04-04T11:41:04.223+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'manual__2025-04-04T11:40:19.330331+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/operators/testdag.py', '--cfg-path', '/tmp/tmp4lav3vtp']
[2025-04-04T11:41:04.227+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask meteo_operations.save_meteo_data
[2025-04-04T11:41:04.229+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T11:41:04.230+0000] {standard_task_runner.py:72} INFO - Started process 180 to run task
[2025-04-04T11:41:04.281+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-04T11:40:19.330331+00:00 [running]> on host d670f735fdc0
[2025-04-04T11:41:04.362+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T11:40:19.330331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T11:40:19.330331+00:00'
[2025-04-04T11:41:04.363+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-04T11:41:04.397+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-04T11:41:04.422+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-04T11:41:04.422+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=manual__2025-04-04T11:40:19.330331+00:00, execution_date=20250404T114019, start_date=20250404T114104, end_date=20250404T114104
[2025-04-04T11:41:04.485+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-04T11:41:04.509+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T11:41:04.512+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
