[2025-04-22T16:49:57.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T16:49:57.871+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-22T16:49:41.671443+00:00 [queued]>
[2025-04-22T16:49:57.880+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-22T16:49:41.671443+00:00 [queued]>
[2025-04-22T16:49:57.881+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-22T16:49:57.891+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-22 16:49:41.671443+00:00
[2025-04-22T16:49:57.897+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'manual__2025-04-22T16:49:41.671443+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpb4d8lu3c']
[2025-04-22T16:49:57.899+0000] {standard_task_runner.py:105} INFO - Job 229: Subtask meteo_operations.save_meteo_data
[2025-04-22T16:49:57.901+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=472) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-22T16:49:57.902+0000] {standard_task_runner.py:72} INFO - Started process 495 to run task
[2025-04-22T16:49:57.940+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-22T16:49:41.671443+00:00 [running]> on host 8e2c8626a9ef
[2025-04-22T16:49:58.017+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T16:49:41.671443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T16:49:41.671443+00:00'
[2025-04-22T16:49:58.019+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T16:49:58.048+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-22T16:49:58.066+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T16:49:58.067+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=manual__2025-04-22T16:49:41.671443+00:00, execution_date=20250422T164941, start_date=20250422T164957, end_date=20250422T164958
[2025-04-22T16:49:58.116+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T16:49:58.133+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T16:49:58.135+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
