[2025-04-15T20:00:12.876+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T20:00:12.887+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data scheduled__2025-04-15T19:00:00+00:00 [queued]>
[2025-04-15T20:00:12.892+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data scheduled__2025-04-15T19:00:00+00:00 [queued]>
[2025-04-15T20:00:12.893+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-15T20:00:12.899+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-15 19:00:00+00:00
[2025-04-15T20:00:12.905+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'scheduled__2025-04-15T19:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmppbbubaz9']
[2025-04-15T20:00:12.906+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask meteo_operations.save_meteo_data
[2025-04-15T20:00:12.907+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=948) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-15T20:00:12.908+0000] {standard_task_runner.py:72} INFO - Started process 970 to run task
[2025-04-15T20:00:12.936+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data scheduled__2025-04-15T19:00:00+00:00 [running]> on host 8e2c8626a9ef
[2025-04-15T20:00:12.994+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-15T19:00:00+00:00'
[2025-04-15T20:00:12.995+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T20:00:13.018+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-15T20:00:13.031+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T20:00:13.032+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=scheduled__2025-04-15T19:00:00+00:00, execution_date=20250415T190000, start_date=20250415T200012, end_date=20250415T200013
[2025-04-15T20:00:13.081+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-15T20:00:13.094+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T20:00:13.096+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
