[2025-02-20T00:00:11.731+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T00:00:11.750+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.openweather_operations.collect_openweather_data scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-20T00:00:11.760+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.openweather_operations.collect_openweather_data scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-20T00:00:11.761+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-20T00:00:11.772+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): openweather_operations.collect_openweather_data> on 2025-02-19 00:00:00+00:00
[2025-02-20T00:00:11.785+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'openweather_operations.collect_openweather_data', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/operators/testdag.py', '--cfg-path', '/tmp/tmpu5ndhblq']
[2025-02-20T00:00:11.788+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask openweather_operations.collect_openweather_data
[2025-02-20T00:00:11.790+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3065) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-20T00:00:11.791+0000] {standard_task_runner.py:72} INFO - Started process 3083 to run task
[2025-02-20T00:00:11.842+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.openweather_operations.collect_openweather_data scheduled__2025-02-19T00:00:00+00:00 [running]> on host b463689998de
[2025-02-20T00:00:11.931+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='openweather_operations.collect_openweather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-20T00:00:11.932+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T00:00:12.382+0000] {logging_mixin.py:190} INFO - Error collecting data for Riyadh: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=24.7136&lon=46.6753&appid=*******************************
[2025-02-20T00:00:12.787+0000] {logging_mixin.py:190} INFO - Error collecting data for Jeddah: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=21.5433&lon=39.1728&appid=*******************************
[2025-02-20T00:00:13.253+0000] {logging_mixin.py:190} INFO - Error collecting data for Mecca: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=21.3891&lon=39.8579&appid=*******************************
[2025-02-20T00:00:13.680+0000] {logging_mixin.py:190} INFO - Error collecting data for Medina: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=24.5247&lon=39.5692&appid=*******************************
[2025-02-20T00:00:14.122+0000] {logging_mixin.py:190} INFO - Error collecting data for Dammam: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=26.4207&lon=50.0888&appid=*******************************
[2025-02-20T00:00:14.643+0000] {logging_mixin.py:190} INFO - Error collecting data for Taif: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=21.4267&lon=40.4833&appid=*******************************
[2025-02-20T00:00:14.644+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-02-20T00:00:14.669+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T00:00:14.670+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=openweather_operations.collect_openweather_data, run_id=scheduled__2025-02-19T00:00:00+00:00, execution_date=20250219T000000, start_date=20250220T000011, end_date=20250220T000014
[2025-02-20T00:00:14.721+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T00:00:14.746+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-20T00:00:14.748+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
