[2025-02-18T19:56:23.006+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T19:56:23.026+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.openweather_operations.collect_openweather_data manual__2025-02-18T19:56:13.160978+00:00 [queued]>
[2025-02-18T19:56:23.035+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.openweather_operations.collect_openweather_data manual__2025-02-18T19:56:13.160978+00:00 [queued]>
[2025-02-18T19:56:23.036+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-18T19:56:23.047+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): openweather_operations.collect_openweather_data> on 2025-02-18 19:56:13.160978+00:00
[2025-02-18T19:56:23.056+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'openweather_operations.collect_openweather_data', 'manual__2025-02-18T19:56:13.160978+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/operators/testdag.py', '--cfg-path', '/tmp/tmpa7hg4_i8']
[2025-02-18T19:56:23.060+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask openweather_operations.collect_openweather_data
[2025-02-18T19:56:23.062+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=823) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T19:56:23.063+0000] {standard_task_runner.py:72} INFO - Started process 841 to run task
[2025-02-18T19:56:23.114+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.openweather_operations.collect_openweather_data manual__2025-02-18T19:56:13.160978+00:00 [running]> on host b463689998de
[2025-02-18T19:56:23.202+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='openweather_operations.collect_openweather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T19:56:13.160978+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T19:56:13.160978+00:00'
[2025-02-18T19:56:23.204+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T19:56:23.651+0000] {logging_mixin.py:190} INFO - Error collecting data for Riyadh: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=24.7136&lon=46.6753&appid=*******************************
[2025-02-18T19:56:24.083+0000] {logging_mixin.py:190} INFO - Error collecting data for Jeddah: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=21.5433&lon=39.1728&appid=*******************************
[2025-02-18T19:56:24.518+0000] {logging_mixin.py:190} INFO - Error collecting data for Mecca: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=21.3891&lon=39.8579&appid=*******************************
[2025-02-18T19:56:24.958+0000] {logging_mixin.py:190} INFO - Error collecting data for Medina: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=24.5247&lon=39.5692&appid=*******************************
[2025-02-18T19:56:25.361+0000] {logging_mixin.py:190} INFO - Error collecting data for Dammam: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=26.4207&lon=50.0888&appid=*******************************
[2025-02-18T19:56:25.776+0000] {logging_mixin.py:190} INFO - Error collecting data for Taif: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?lat=21.4267&lon=40.4833&appid=*******************************
[2025-02-18T19:56:25.776+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-02-18T19:56:25.803+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T19:56:25.803+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=openweather_operations.collect_openweather_data, run_id=manual__2025-02-18T19:56:13.160978+00:00, execution_date=20250218T195613, start_date=20250218T195623, end_date=20250218T195625
[2025-02-18T19:56:25.847+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T19:56:25.873+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T19:56:25.875+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
