[2025-04-15T16:00:14.042+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T16:00:14.060+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data scheduled__2025-04-15T15:00:00+00:00 [queued]>
[2025-04-15T16:00:14.066+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data scheduled__2025-04-15T15:00:00+00:00 [queued]>
[2025-04-15T16:00:14.067+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-15T16:00:14.076+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-15 15:00:00+00:00
[2025-04-15T16:00:14.082+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'scheduled__2025-04-15T15:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp4h4z66g5']
[2025-04-15T16:00:14.084+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask meteo_operations.save_meteo_data
[2025-04-15T16:00:14.085+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1388) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-15T16:00:14.086+0000] {standard_task_runner.py:72} INFO - Started process 1410 to run task
[2025-04-15T16:00:14.120+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data scheduled__2025-04-15T15:00:00+00:00 [running]> on host 9b6a771fafd5
[2025-04-15T16:00:14.184+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-15T15:00:00+00:00'
[2025-04-15T16:00:14.185+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T16:00:14.213+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-15T16:00:14.230+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T16:00:14.231+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=scheduled__2025-04-15T15:00:00+00:00, execution_date=20250415T150000, start_date=20250415T160014, end_date=20250415T160014
[2025-04-15T16:00:14.260+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-15T16:00:14.280+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T16:00:14.281+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
