[2025-04-20T21:24:14.532+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T21:24:14.550+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T21:23:59.392682+00:00 [queued]>
[2025-04-20T21:24:14.557+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T21:23:59.392682+00:00 [queued]>
[2025-04-20T21:24:14.558+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T21:24:14.567+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-20 21:23:59.392682+00:00
[2025-04-20T21:24:14.573+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'manual__2025-04-20T21:23:59.392682+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmprpe8cv8v']
[2025-04-20T21:24:14.574+0000] {standard_task_runner.py:105} INFO - Job 145: Subtask meteo_operations.save_meteo_data
[2025-04-20T21:24:14.575+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1472) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-20T21:24:14.576+0000] {standard_task_runner.py:72} INFO - Started process 1494 to run task
[2025-04-20T21:24:14.607+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T21:23:59.392682+00:00 [running]> on host 8e2c8626a9ef
[2025-04-20T21:24:14.665+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T21:23:59.392682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T21:23:59.392682+00:00'
[2025-04-20T21:24:14.666+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T21:24:14.691+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-20T21:24:14.708+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T21:24:14.709+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=manual__2025-04-20T21:23:59.392682+00:00, execution_date=20250420T212359, start_date=20250420T212414, end_date=20250420T212414
[2025-04-20T21:24:14.751+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-20T21:24:14.770+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T21:24:14.772+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
