[2025-04-20T22:21:46.252+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T22:21:46.265+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:19:25.570299+00:00 [queued]>
[2025-04-20T22:21:46.272+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:19:25.570299+00:00 [queued]>
[2025-04-20T22:21:46.273+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T22:21:46.281+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-20 22:19:25.570299+00:00
[2025-04-20T22:21:46.287+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'manual__2025-04-20T22:19:25.570299+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp2_7v1__z']
[2025-04-20T22:21:46.288+0000] {standard_task_runner.py:105} INFO - Job 170: Subtask meteo_operations.save_meteo_data
[2025-04-20T22:21:46.289+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=406) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-20T22:21:46.290+0000] {standard_task_runner.py:72} INFO - Started process 428 to run task
[2025-04-20T22:21:46.318+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:19:25.570299+00:00 [running]> on host 8e2c8626a9ef
[2025-04-20T22:21:46.376+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T22:19:25.570299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T22:19:25.570299+00:00'
[2025-04-20T22:21:46.377+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T22:21:46.397+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-20T22:21:46.412+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T22:21:46.413+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=manual__2025-04-20T22:19:25.570299+00:00, execution_date=20250420T221925, start_date=20250420T222146, end_date=20250420T222146
[2025-04-20T22:21:46.464+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-20T22:21:46.481+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-20T22:21:46.483+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
