[2025-04-20T22:53:56.354+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T22:53:56.371+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:53:35.945068+00:00 [queued]>
[2025-04-20T22:53:56.379+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:53:35.945068+00:00 [queued]>
[2025-04-20T22:53:56.379+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T22:53:56.390+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-20 22:53:35.945068+00:00
[2025-04-20T22:53:56.399+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'manual__2025-04-20T22:53:35.945068+00:00', '--job-id', '714', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp20c15c1n']
[2025-04-20T22:53:56.402+0000] {standard_task_runner.py:105} INFO - Job 714: Subtask meteo_operations.save_meteo_data
[2025-04-20T22:53:56.406+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2480) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-20T22:53:56.407+0000] {standard_task_runner.py:72} INFO - Started process 2498 to run task
[2025-04-20T22:53:56.452+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:53:35.945068+00:00 [running]> on host 3ec408313633
[2025-04-20T22:53:56.538+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T22:53:35.945068+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T22:53:35.945068+00:00'
[2025-04-20T22:53:56.540+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T22:53:56.578+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-20T22:53:56.603+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T22:53:56.604+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=manual__2025-04-20T22:53:35.945068+00:00, execution_date=20250420T225335, start_date=20250420T225356, end_date=20250420T225356
[2025-04-20T22:53:56.662+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-20T22:53:56.689+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T22:53:56.691+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
